services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app/api
    environment:
      API_SERVER_ADDR: "3000"
      DATABASE_URL: postgres://local-dev@db/api?sslmode=disable
      MON_NLP_GRPC_ADDR: "50051"
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: local-dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  pgadmin:
    profiles: ["pgadmin"]
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mon.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  migrate: &basemigrate
    profiles: ["tools"]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations
  migrate-down:
    <<: *basemigrate
    command: down
  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""
volumes:
  data:
  pgadmin-data:
