// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DeletedKanji defines model for DeletedKanji.
type DeletedKanji struct {
	Id string `json:"id"`
}

// DeletedReading defines model for DeletedReading.
type DeletedReading struct {
	Id string `json:"id"`
}

// Kanji defines model for Kanji.
type Kanji struct {
	ExampleSentences string             `json:"exampleSentences"`
	ExampleWords     string             `json:"exampleWords"`
	Id               openapi_types.UUID `json:"id"`
	Kanji            string             `json:"kanji"`
	KanjiRating      string             `json:"kanjiRating"`
	KunReading       string             `json:"kunReading"`
	Meanings         *string            `json:"meanings,omitempty"`
	OnReading        string             `json:"onReading"`
	Username         string             `json:"username"`
}

// Kanjis defines model for Kanjis.
type Kanjis struct {
	Kanjis []Kanji `json:"kanjis"`
}

// PostKanji defines model for PostKanji.
type PostKanji struct {
	ExampleSentences string `json:"exampleSentences"`
	ExampleWords     string `json:"exampleWords"`
	Kanji            string `json:"kanji"`
	KanjiRating      int    `json:"kanjiRating"`
	KunReading       string `json:"kunReading"`
	Meanings         string `json:"meanings"`
	OnReading        string `json:"onReading"`
	Username         string `json:"username"`
}

// PostReading defines model for PostReading.
type PostReading struct {
	Japanese    string `json:"japanese"`
	Title       string `json:"title"`
	Translation string `json:"translation"`
	Username    string `json:"username"`
}

// PostVocab defines model for PostVocab.
type PostVocab struct {
	Definitions      string `json:"definitions"`
	ExampleSentences string `json:"exampleSentences"`
	Kanji            string `json:"kanji"`
	PartsOfSpeech    string `json:"partsOfSpeech"`
	Username         string `json:"username"`
	Vocab            string `json:"vocab"`
	VocabRating      int    `json:"vocabRating"`
}

// Reading defines model for Reading.
type Reading struct {
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Japanese    string              `json:"japanese"`
	Title       string              `json:"title"`
	Translation string              `json:"translation"`
}

// Readings defines model for Readings.
type Readings struct {
	Readings []Reading `json:"readings"`
}

// Vocab defines model for Vocab.
type Vocab struct {
	Definitions      string `json:"definitions"`
	ExampleSentences string `json:"exampleSentences"`
	Id               string `json:"id"`
	Kanji            string `json:"kanji"`
	PartsOfSpeech    string `json:"partsOfSpeech"`
	Username         string `json:"username"`
	Vocab            string `json:"vocab"`
	VocabRating      int    `json:"vocabRating"`
}

// DeleteVocabParams defines parameters for DeleteVocab.
type DeleteVocabParams struct {
	// Username The username for whom all vocabulary are requested
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Limit The amount of vocabulary to be requested
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Id The id of the vocabulary that is to be deleted
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetVocabParams defines parameters for GetVocab.
type GetVocabParams struct {
	// Username The username for whom all vocabulary are requested
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Limit The amount of vocabulary to be requested
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Id The id of the vocabulary that is to be deleted
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// UpdateVocabParams defines parameters for UpdateVocab.
type UpdateVocabParams struct {
	// Username The username for whom all vocabulary are requested
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Limit The amount of vocabulary to be requested
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Id The id of the vocabulary that is to be deleted
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// AddVocabParams defines parameters for AddVocab.
type AddVocabParams struct {
	// Username The username for whom all vocabulary are requested
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Limit The amount of vocabulary to be requested
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Id The id of the vocabulary that is to be deleted
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// UpdateKanjiJSONRequestBody defines body for UpdateKanji for application/json ContentType.
type UpdateKanjiJSONRequestBody = Kanji

// AddKanjiJSONRequestBody defines body for AddKanji for application/json ContentType.
type AddKanjiJSONRequestBody = PostKanji

// UpdateReadingJSONRequestBody defines body for UpdateReading for application/json ContentType.
type UpdateReadingJSONRequestBody = Reading

// CreateReadingJSONRequestBody defines body for CreateReading for application/json ContentType.
type CreateReadingJSONRequestBody = PostReading

// UpdateVocabJSONRequestBody defines body for UpdateVocab for application/json ContentType.
type UpdateVocabJSONRequestBody = Vocab

// AddVocabJSONRequestBody defines body for AddVocab for application/json ContentType.
type AddVocabJSONRequestBody = PostVocab
