// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DeletedKanji defines model for DeletedKanji.
type DeletedKanji struct {
	Id string `json:"id"`
}

// DeletedReading defines model for DeletedReading.
type DeletedReading struct {
	Id string `json:"id"`
}

// Kanji defines model for Kanji.
type Kanji struct {
	ExampleSentences string             `json:"exampleSentences"`
	ExampleWords     string             `json:"exampleWords"`
	Id               openapi_types.UUID `json:"id"`
	Kanji            string             `json:"kanji"`
	KanjiRating      string             `json:"kanjiRating"`
	KunReading       string             `json:"kunReading"`
	Meanings         *string            `json:"meanings,omitempty"`
	OnReading        string             `json:"onReading"`
	Username         string             `json:"username"`
}

// Kanjis defines model for Kanjis.
type Kanjis struct {
	Readings *[]Kanji `json:"readings,omitempty"`
}

// PostKanji defines model for PostKanji.
type PostKanji struct {
	ExampleSentences string `json:"exampleSentences"`
	ExampleWords     string `json:"exampleWords"`
	Kanji            string `json:"kanji"`
	KanjiRating      int    `json:"kanjiRating"`
	KunReading       string `json:"kunReading"`
	Meanings         string `json:"meanings"`
	OnReading        string `json:"onReading"`
	Username         string `json:"username"`
}

// PostReading defines model for PostReading.
type PostReading struct {
	Japanese    string `json:"japanese"`
	Title       string `json:"title"`
	Translation string `json:"translation"`
	Username    string `json:"username"`
}

// Reading defines model for Reading.
type Reading struct {
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Japanese    string              `json:"japanese"`
	Title       string              `json:"title"`
	Translation string              `json:"translation"`
}

// Readings defines model for Readings.
type Readings struct {
	Readings []Reading `json:"readings"`
}

// UpdateKanjiJSONRequestBody defines body for UpdateKanji for application/json ContentType.
type UpdateKanjiJSONRequestBody = Kanji

// AddKanjiJSONRequestBody defines body for AddKanji for application/json ContentType.
type AddKanjiJSONRequestBody = PostKanji

// UpdateReadingJSONRequestBody defines body for UpdateReading for application/json ContentType.
type UpdateReadingJSONRequestBody = Reading

// CreateReadingJSONRequestBody defines body for CreateReading for application/json ContentType.
type CreateReadingJSONRequestBody = PostReading
