openapi: "3.1.0"
info: 
  version: 1.0.0
  title: Mon
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /reading:
    get:
      operationId: getReadings
      responses:
        '200':
          description: Readings that have been found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Readings'
    post:
      operationId: createReading
      requestBody:
        description: The title, japanese text, and translation required for creating a reading
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostReading'
      responses:
        '201':
          description: The reading that has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
    patch:
      operationId: updateReading
      requestBody:
        description: The title, japanese text, and translation that should be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reading'
      responses:
        '200':
          description: The reading has been updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
    delete:
      operationId: deleteReading
      responses:
        '200':
          description: The id of the reading that has been deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletedReading'


components:
  schemas:
    Reading:
      type: object
      required: [translation, japanese, title]
      properties:
        translation:
          type: string
        japanese:
          type: string
        title:
          type: string
        id:
          type: string
          format: uuid
    Readings:
      type: object
      required: [readings]
      properties:
        readings:
          type: array
          items:
            $ref: '#/components/schemas/Reading'
    PostReading:
      type: object
      required: [translation, japanese, title]
      properties:
        translation:
          type: string
          example: "A text in any language"
        japanese:
          type: string
          example: "これは日本語の原文です"
        title:
          type: string
          example: "A descriptive text of the original japanese text"
    DeletedReading:
      type: object
      required: [id]
      properties:
        id:
          type: string
